export type PlaceCategoryId =
  | "aeropuerto"
  | "tren"
  | "animales"
  | "cultural"
  | "monumento"
  | "religiones"
  | "playa"
  | "mercados"
  | "deportes"
  | "barca";

export type PlaceCategory = {
  id: PlaceCategoryId;
  label: string;
  description: string;
  color: string;
};

export const PLACE_CATEGORIES: PlaceCategory[] = [
  {
    id: "aeropuerto",
    label: "Aeropuerto",
    description: "Mapa del aeropuerto de Barcelona",
    color: "#0ea5e9",
  },
  {
    id: "tren",
    label: "Estación de tren",
    description: "Estación de tren",
    color: "#f59e0b",
  },
  {
    id: "animales",
    label: "Zoo o acuario",
    description: "Zoo o acuario",
    color: "#10b981",
  },
  {
    id: "cultural",
    label: "Cultural",
    description: "Museos, edificio histórico, Gaudí, etc.",
    color: "#8b5cf6",
  },
  {
    id: "monumento",
    label: "Monumento importante",
    description: "Monumento o zona importante",
    color: "#f43f5e",
  },
  {
    id: "religiones",
    label: "Religioso",
    description: "Monumento de carácter religioso",
    color: "#d946ef",
  },
  {
    id: "playa",
    label: "Playa",
    description: "Zona de playa o marítima",
    color: "#3b82f6",
  },
  {
    id: "mercados",
    label: "Mercados",
    description: "Mercados municipales increíbles",
    color: "#f97316",
  },
  {
    id: "deportes",
    label: "Deportes",
    description: "Relacionado con deportes",
    color: "#14b8a6",
  },
  {
    id: "barca",
    label: "Barça",
    description: "Relacionado con el FC Barcelona",
    color: "#dc2626",
  },
];

export function getCategory(id: PlaceCategoryId): PlaceCategory {
  return (
    PLACE_CATEGORIES.find((category) => category.id === id) ??
    PLACE_CATEGORIES[PLACE_CATEGORIES.length - 1]
  );
}

export type PlacePoint = {
  id: string;
  category: PlaceCategoryId;
  nameEs: string;
  nameCa: string;
  address?: string;
  lat: number;
  lng: number;
  placeId?: string;
};

export type PlaceAutocompleteItem = {
  placeId: string;
  description: string;
};

export const initialPoints: PlacePoint[] = [
  {
    id: "p01",
    category: "aeropuerto",
    nameEs: "Aeropuerto de Barcelona",
    nameCa: "Aeroport de Barcelona (El Prat)",
    address: "El Prat de Llobregat, Barcelona",
    lat: 41.297445,
    lng: 2.083295,
  },
  {
    id: "p02",
    category: "barca",
    nameEs: "Estadio Camp Nou",
    nameCa: "Estadi Camp Nou",
    address: "C. d'Arístides Maillol, 12",
    lat: 41.380898,
    lng: 2.12282,
  },
  {
    id: "p03",
    category: "tren",
    nameEs: "Estación de Sants",
    nameCa: "Estació de Sants",
    address: "Pl. dels Països Catalans, s/n",
    lat: 41.37933,
    lng: 2.14035,
  },
  {
    id: "p04",
    category: "monumento",
    nameEs: "Parque de la España Industrial",
    nameCa: "Parc de l'Espanya Industrial",
    address: "Carrer de Muntades, Sants-Montjuïc",
    lat: 41.3755,
    lng: 2.14055,
  },
  {
    id: "p05",
    category: "monumento",
    nameEs: "Plaza de España",
    nameCa: "Plaça d'Espanya",
    address: "Sants-Montjuïc",
    lat: 41.3751,
    lng: 2.1497,
  },
  {
    id: "p06",
    category: "monumento",
    nameEs: "Fuente Mágica de Montjuïc",
    nameCa: "Font Màgica de Montjuïc",
    address: "Pl. de Carles Buïgas, 1",
    lat: 41.3714,
    lng: 2.15,
  },
  {
    id: "p07",
    category: "cultural",
    nameEs: "Fundació Miró",
    nameCa: "Fundació Joan Miró",
    address: "Parc de Montjuïc, s/n",
    lat: 41.3684,
    lng: 2.1599,
  },
  {
    id: "p08",
    category: "cultural",
    nameEs: "MNAC",
    nameCa: "Museu Nacional d'Art de Catalunya",
    address: "Palau Nacional, Parc de Montjuïc",
    lat: 41.3686,
    lng: 2.1531,
  },
  {
    id: "p09",
    category: "deportes",
    nameEs: "Parque Olímpico",
    nameCa: "Parc Olímpic de Montjuïc",
    address: "Anella Olímpica de Montjuïc",
    lat: 41.3642,
    lng: 2.1555,
  },
  {
    id: "p10",
    category: "deportes",
    nameEs: "Palau Sant Jordi",
    nameCa: "Palau Sant Jordi",
    address: "Passeig Olímpic, 5-7",
    lat: 41.3633,
    lng: 2.1526,
  },
  {
    id: "p11",
    category: "monumento",
    nameEs: "Teleférico de Montjuïc",
    nameCa: "Telefèric de Montjuïc",
    address: "Avinguda del Miramar, 30",
    lat: 41.3706,
    lng: 2.1699,
  },
  {
    id: "p12",
    category: "monumento",
    nameEs: "Castillo de Montjuïc",
    nameCa: "Castell de Montjuïc",
    address: "Ctra. de Montjuïc, 66",
    lat: 41.3636,
    lng: 2.1664,
  },
  {
    id: "p13",
    category: "monumento",
    nameEs: "Teleférico del puerto",
    nameCa: "Transbordador Aeri del Port",
    address: "Passeig Joan de Borbó, 93",
    lat: 41.3743,
    lng: 2.1886,
  },
  {
    id: "p14",
    category: "monumento",
    nameEs: "World Trade Center Barcelona",
    nameCa: "World Trade Center Barcelona",
    address: "Moll de Barcelona, s/n",
    lat: 41.3716,
    lng: 2.1798,
  },
  {
    id: "p15",
    category: "playa",
    nameEs: "Maremagnum",
    nameCa: "Maremagnum",
    address: "Moll d'Espanya, 5",
    lat: 41.3754,
    lng: 2.1839,
  },
  {
    id: "p16",
    category: "monumento",
    nameEs: "Estatua de Colón",
    nameCa: "Monument a Colom",
    address: "Pl. del Portal de la Pau, s/n",
    lat: 41.3755,
    lng: 2.1774,
  },
  {
    id: "p17",
    category: "animales",
    nameEs: "Acuario de Barcelona",
    nameCa: "L'Aquàrium de Barcelona",
    address: "Moll d'Espanya del Port Vell",
    lat: 41.3763,
    lng: 2.184,
  },
  {
    id: "p18",
    category: "playa",
    nameEs: "Playa Barceloneta",
    nameCa: "Platja de la Barceloneta",
    address: "Passeig Marítim de la Barceloneta",
    lat: 41.3807,
    lng: 2.1944,
  },
  {
    id: "p19",
    category: "tren",
    nameEs: "Estación de Francia",
    nameCa: "Estació de França",
    address: "Av. del Marquès de l'Argentera, s/n",
    lat: 41.3842,
    lng: 2.1855,
  },
  {
    id: "p20",
    category: "monumento",
    nameEs: "Parque de la Ciutadella",
    nameCa: "Parc de la Ciutadella",
    address: "Passeig de Picasso, 21",
    lat: 41.388,
    lng: 2.186,
  },
  {
    id: "p21",
    category: "playa",
    nameEs: "Playa Vila Olímpica",
    nameCa: "Platja de la Vila Olímpica",
    address: "Passeig Marítim de la Barceloneta",
    lat: 41.3917,
    lng: 2.2077,
  },
  {
    id: "p22",
    category: "deportes",
    nameEs: "Puerto Olímpico",
    nameCa: "Port Olímpic",
    address: "Moll de la Marina, s/n",
    lat: 41.3866,
    lng: 2.202,
  },
  {
    id: "p23",
    category: "animales",
    nameEs: "Zoológico de Barcelona",
    nameCa: "Zoo de Barcelona",
    address: "Parc de la Ciutadella, s/n",
    lat: 41.3855,
    lng: 2.1922,
  },
  {
    id: "p24",
    category: "religiones",
    nameEs: "Catedral de Barcelona",
    nameCa: "Catedral de Barcelona",
    address: "Pla de la Seu, s/n",
    lat: 41.3841,
    lng: 2.1763,
  },
  {
    id: "p25",
    category: "mercados",
    nameEs: "Mercado de la Boquería",
    nameCa: "Mercat de la Boqueria",
    address: "La Rambla, 91",
    lat: 41.3818,
    lng: 2.1719,
  },
  {
    id: "p26",
    category: "cultural",
    nameEs: "Museo de Historia de Barcelona",
    nameCa: "Museu d'Història de Barcelona",
    address: "Pl. del Rei, s/n",
    lat: 41.3838,
    lng: 2.1778,
  },
  {
    id: "p27",
    category: "religiones",
    nameEs: "Santa Maria del Mar",
    nameCa: "Basílica de Santa Maria del Mar",
    address: "Pl. de Santa Maria, 1",
    lat: 41.3839,
    lng: 2.1814,
  },
  {
    id: "p28",
    category: "cultural",
    nameEs: "MACBA",
    nameCa: "Museu d'Art Contemporani de Barcelona",
    address: "Pl. dels Àngels, 1",
    lat: 41.3831,
    lng: 2.1669,
  },
  {
    id: "p29",
    category: "monumento",
    nameEs: "Plaza de Catalunya",
    nameCa: "Plaça de Catalunya",
    address: "Plaça de Catalunya",
    lat: 41.387,
    lng: 2.17,
  },
  {
    id: "p30",
    category: "barca",
    nameEs: "Fuente de Canaletes",
    nameCa: "Font de Canaletes",
    address: "La Rambla, 122",
    lat: 41.3865,
    lng: 2.1711,
  },
  {
    id: "p31",
    category: "cultural",
    nameEs: "Casa Batlló",
    nameCa: "Casa Batlló",
    address: "Pg. de Gràcia, 43",
    lat: 41.3917,
    lng: 2.165,
  },
  {
    id: "p32",
    category: "cultural",
    nameEs: "Farolas de Gaudí",
    nameCa: "Fanals de Gaudí",
    address: "Plaça Reial",
    lat: 41.38,
    lng: 2.1753,
  },
  {
    id: "p33",
    category: "cultural",
    nameEs: "Casa Calvet",
    nameCa: "Casa Calvet",
    address: "C. de Casp, 48",
    lat: 41.3897,
    lng: 2.169,
  },
  {
    id: "p34",
    category: "mercados",
    nameEs: "Mercado de Santa Caterina",
    nameCa: "Mercat de Santa Caterina",
    address: "Av. de Francesc Cambó, 16",
    lat: 41.387,
    lng: 2.1783,
  },
  {
    id: "p35",
    category: "cultural",
    nameEs: "Palau de la Música Catalana",
    nameCa: "Palau de la Música Catalana",
    address: "C. del Palau de la Música, 4",
    lat: 41.3875,
    lng: 2.1753,
  },
  {
    id: "p36",
    category: "monumento",
    nameEs: "Arco de Triunfo",
    nameCa: "Arc de Triomf",
    address: "Pg. de Lluís Companys, s/n",
    lat: 41.3911,
    lng: 2.1808,
  },
  {
    id: "p37",
    category: "tren",
    nameEs: "Estación del Norte",
    nameCa: "Estació del Nord",
    address: "C. de Nàpols, 190",
    lat: 41.3933,
    lng: 2.1864,
  },
  {
    id: "p38",
    category: "monumento",
    nameEs: "Torre Glòries",
    nameCa: "Torre Glòries",
    address: "Av. Diagonal, 211",
    lat: 41.4036,
    lng: 2.1904,
  },
  {
    id: "p39",
    category: "monumento",
    nameEs: "Fórum de las Culturas",
    nameCa: "Parc del Fòrum",
    address: "Av. Diagonal, 93",
    lat: 41.411,
    lng: 2.224,
  },
  {
    id: "p40",
    category: "cultural",
    nameEs: "La Pedrera (Casa Milà)",
    nameCa: "Casa Milà (La Pedrera)",
    address: "Pg. de Gràcia, 92",
    lat: 41.3953,
    lng: 2.1619,
  },
  {
    id: "p41",
    category: "cultural",
    nameEs: "Casa de las Punxes",
    nameCa: "Casa de les Punxes",
    address: "Av. Diagonal, 416",
    lat: 41.3967,
    lng: 2.1617,
  },
  {
    id: "p42",
    category: "religiones",
    nameEs: "Sagrada Família",
    nameCa: "Basílica de la Sagrada Família",
    address: "C. de Mallorca, 401",
    lat: 41.4036,
    lng: 2.1744,
  },
  {
    id: "p43",
    category: "monumento",
    nameEs: "Hospital de Sant Pau",
    nameCa: "Recinte Modernista de Sant Pau",
    address: "C. de Sant Antoni Maria Claret, 167",
    lat: 41.4136,
    lng: 2.1742,
  },
  {
    id: "p44",
    category: "cultural",
    nameEs: "Dragón de Gaudí",
    nameCa: "Drac de Gaudí",
    address: "Park Güell, Ctra. del Carmel",
    lat: 41.4142,
    lng: 2.1526,
  },
  {
    id: "p45",
    category: "cultural",
    nameEs: "Parc Güell",
    nameCa: "Park Güell",
    address: "Ctra. del Carmel, s/n",
    lat: 41.4145,
    lng: 2.1527,
  },
  {
    id: "p46",
    category: "cultural",
    nameEs: "CosmoCaixa",
    nameCa: "Museu de la Ciència CosmoCaixa",
    address: "C. d'Isaac Newton, 26",
    lat: 41.4134,
    lng: 2.1364,
  },
  {
    id: "p47",
    category: "cultural",
    nameEs: "Torre Bellesguard",
    nameCa: "Torre Bellesguard",
    address: "C. de Bellesguard, 20",
    lat: 41.4094,
    lng: 2.1287,
  },
  {
    id: "p48",
    category: "religiones",
    nameEs: "Monasterio de Pedralbes",
    nameCa: "Monestir de Pedralbes",
    address: "Baixada del Monestir, 9",
    lat: 41.3958,
    lng: 2.1092,
  },
  {
    id: "p49",
    category: "monumento",
    nameEs: "Torre de Collserola",
    nameCa: "Torre de Collserola",
    address: "Ctra. de Vallvidrera al Tibidabo",
    lat: 41.4169,
    lng: 2.0928,
  },
];
